import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AudioPlayer from "../components/ui/audio-player";
import QueryProvider from "../app/providers/query-provider";
import Footer from "../components/ui/footer";
import Header from "../components/ui/header";
import { AudioProvider } from "./providers/audio-provider";
import GlobalClickSound from "@/components/globalClickSound";
import { PackLockProvider } from "./providers/pack-lock-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Star Wars TCG Collection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          paddingBottom: "80px",
          paddingTop: "80px"
        }}
      >
        <QueryProvider>
          <AudioProvider>
            <PackLockProvider>
              <GlobalClickSound />
              <Header />
              {children}
              <AudioPlayer />
              <Footer />
              <audio id="bgMusic" src="/music/track.mp3" loop preload="auto" />
            </PackLockProvider>
          </AudioProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
