import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AudioPlayer from "../components/ui/audio-player";
import Footer from "../components/ui/footer";
import Header from "../components/ui/header";
import { AudioProvider } from "./providers";
import GlobalClickSound from "@/components/globalClickSound";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Star Wars TCG Collection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          minHeight: "100vh",
          position: "relative",
          paddingBottom: "120px",
          paddingTop: "160px" // Espacio para el header
        }}
      >
        <AudioProvider>
          <GlobalClickSound />
          <Header />
          {children}
          <AudioPlayer />
          <Footer />
          <audio id="bgMusic" src="/music/track.mp3" loop preload="auto" />
        </AudioProvider>
      </body>
    </html>
  );
}
